### ISSUE TITLE
missing yolo.h5

### ISSUE THREAD

**Issue by ujjawalcse** [TheAnkurGoswami/Human-Violence-Detection#4]
Hi @TheAnkurGoswami,
I'm trying to execute your code.
But yolo.h5 is missing in the models folder. 
Can you please provide the links for downloading your yolo.h5??
openpose.h5 was also missing but I got it from the link you provided in the first issue.

**Comment by TheAnkurGoswami** [comment]
Fixed it. Find links in the Readme file.
